CXXFLAGS= -std=c++11 -g
CPPFLAGS=-I/usr/local/include/SDL2 -I/usr/include/mingw -Dmain=SDL_main -I. 
LDFLAGS=-L/usr/local/lib 
LDLIBS=-lcygwin -lSDL2_image -lSDL2main -lSDL2
TARGET=cubicle

$(TARGET):

.PHONY: clean

clean:
	rm $(TARGET)
